### ISSUE TITLE
Entity issue

### ISSUE THREAD

**Issue by SeymurMammadrza** [ColdTea-Projects/verborum_ms#9]
https://github.com/ColdTea-Projects/verborum_ms/blob/c47d32c133b9cbb5b4de52d0351ec23278fd3a3b/ms_dictionary/src/main/java/de/coldtea/verborum/msdictionary/dictionary/repository/Dictionary.java#L9

ID icin generation strategy olusturalım. UUİD ile generate etsin bence. ya da, bi seq table olusturalım ki, sequence generator olsun. Bu tarz: 

```
    @Id
    @SequenceGenerator(name = "card_details_seq",
            sequenceName = "CARD_DETAILS_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "card_details_seq")
    private Long id;
```
    
    Mesela bu da burdaki entity nin table scripti, yamlda : 
    
  ```
  databaseChangeLog:
  - changeSet:
      id: createActDetailsTable
      author: seymur.mammadrza
      changes:
        - createTable:
            tableName: act_details
            schemaName: card_delivery
            columns:
              - column:
                  name: id
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: act_number
                  type: varchar(64)
              - column:
                  name: act_dt
                  type: timestamp
              - column:
                  name: act_branch
                  type: varchar(64)
              - column:
                  name: batch_no
                  type: varchar(255)
              - column:
                  name: status
                  type: varchar(255)
              - column:
                  name: description
                  type: varchar(255)
              - column:
                  name: created_dt
                  type: timestamp
              - column:
                  name: updated_dt
                  type: timestamp

  - changeSet:
      id: createActDetailsSequence
      author: seymur.mammadrza
      changes:
        - createSequence:
            sequenceName: ACT_DETAILS_SEQ
            schemaName: card_delivery
            startValue: 1
            incrementBy: 1

```

Artı, tüm getter setterları constructorları yazmana gerek yok. Lombok annotationları kullan bence. @Getter @Setter @NoArgsConstructor @AllArgsConstructor gibi. Spring kendisi generate etsin
